Repository siemens/continuous-clearing, pull requests merged in 2025-09, with the labels that each got.

#311 feat: Compliance Exception warning's
  TestFiles/IntegrationTestFiles/SystemTest1stIterationData/ComplienceCheckNugetFolder/packages.config
  doc/UsageDoc/CA_UsageDocument.md
  src/AritfactoryUploader.UTest/PackageUploadHelperTest.cs
  src/LCT.APICommunications/AttachmentHelper.cs
  src/LCT.Common.UTests/ComplianceCheckTest.cs
  src/LCT.Common/CommonHelper.cs
  src/LCT.Common/ComplianceValidator/ComplianceCheck.cs
  src/LCT.Common/ComplianceValidator/ComplianceSettings.json
  src/LCT.Common/Interface/IChecker.cs
  src/LCT.Common/Interface/IPrintRecommendation.cs
  src/LCT.Common/Interface/IPrintWarning.cs
  src/LCT.Common/LCT.Common.csproj
  src/LCT.Common/Model/ComlianceValidator.cs
  src/LCT.Common/PipelineArtifactUploader.cs
  src/LCT.PackageIdentifier/Model/ComponentsInfo.cs
  src/LCT.SW360PackageCreator/Program.cs
  src/SW360IntegrationTest/Nuget/ComplianceCheckIntegrationNuget.cs
  src/SW360IntegrationTest/PackageCreatorTestFiles/Nuget/CCTComplienceCheckComparisonBOMNugetInitial.json
Labels: enhancement, work in progress, to be planned, Importance Low

#327 fix: Bug fix while creating and updating components in SW360 . Validate component with purlid.
  src/LCT.Common.UTests/CommonHelperTest.cs
  src/LCT.Common/CommonHelper.cs
  src/LCT.Common/Model/Components.cs
  src/LCT.SW360PackageCreator/CreatorHelper.cs
  src/LCT.Services.UTest/Sw360ServiceTest.cs
  src/LCT.Services/Interface/ISW360Service.cs
  src/LCT.Services/Sw360Service.cs
Labels: bug, Importance High

#334 fix: Update sourcecode url and source code folder format in sw360
  .github/workflows/build-and-release.yml
  CA.nuspec
  src/ArtifactoryUploader/LCT.ArtifactoryUploader.csproj
  src/LCT.APICommunications/LCT.APICommunications.csproj
  src/LCT.Common/LCT.Common.csproj
  src/LCT.CycloneDxProcessor/LCT.CycloneDxProcessor.csproj
  src/LCT.Facade/LCT.Facade.csproj
  src/LCT.PackageIdentifier/LCT.PackageIdentifier.csproj
  src/LCT.SW360PackageCreator/LCT.SW360PackageCreator.csproj
  src/LCT.SW360PackageCreator/PackageDownloader.cs
  src/LCT.Services/LCT.Services.csproj
  src/LCT.Telemetry/LCT.Telemetry.csproj
  src/SW360IntegrationTest/NPM/ComponentCreatorInitial.cs
  src/SW360IntegrationTest/Nuget/ComponentCreatorInitialNuget.cs
Labels: bug, Importance High

#336 fix: v8.2.1
  .github/workflows/build-and-release.yml
  CA.nuspec
  src/ArtifactoryUploader/LCT.ArtifactoryUploader.csproj
  src/LCT.APICommunications/LCT.APICommunications.csproj
  src/LCT.Common.UTests/CommonHelperTest.cs
  src/LCT.Common/CommonHelper.cs
  src/LCT.Common/LCT.Common.csproj
  src/LCT.Common/Model/Components.cs
  src/LCT.CycloneDxProcessor/LCT.CycloneDxProcessor.csproj
  src/LCT.Facade/LCT.Facade.csproj
  src/LCT.PackageIdentifier/LCT.PackageIdentifier.csproj
  src/LCT.SW360PackageCreator/CreatorHelper.cs
  src/LCT.SW360PackageCreator/LCT.SW360PackageCreator.csproj
  src/LCT.SW360PackageCreator/PackageDownloader.cs
  src/LCT.Services.UTest/Sw360ServiceTest.cs
  src/LCT.Services/Interface/ISW360Service.cs
  src/LCT.Services/LCT.Services.csproj
  src/LCT.Services/Sw360Service.cs
  src/LCT.Telemetry/LCT.Telemetry.csproj
  src/SW360IntegrationTest/NPM/ComponentCreatorInitial.cs
  src/SW360IntegrationTest/Nuget/ComponentCreatorInitialNuget.cs
Labels: bug, Importance High

#328 feat: Exact Dotnet Runtime in SBOM updated
  src/LCT.PackageIdentifier.UTest/BomHelperUnitTests.cs
  src/LCT.PackageIdentifier.UTest/CompositionBuilderTests.cs
  src/LCT.PackageIdentifier.UTest/DotnetRuntimeIdentiferTests.cs
  src/LCT.PackageIdentifier.UTest/NugetDevDependencyParserTests.cs
  src/LCT.PackageIdentifier.UTest/NugetParserTests.cs
  src/LCT.PackageIdentifier/BomCreator.cs
  src/LCT.PackageIdentifier/CompositionBuilder.cs
  src/LCT.PackageIdentifier/DotnetRuntimeIdentifer.cs
  src/LCT.PackageIdentifier/Interface/ICompositionBuilder.cs
  src/LCT.PackageIdentifier/Interface/IRuntimeIdentifier.cs
  src/LCT.PackageIdentifier/Model/RuntimeInfo.cs
  src/LCT.PackageIdentifier/NugetDevDependencyParser.cs
  src/LCT.PackageIdentifier/NugetProcessor.cs
  src/LCT.PackageIdentifier/Program.cs
Labels: enhancement, to be planned, Importance Low, Under Review

#343 feat: Choco packages testcase updated for Choco.
  TestFiles/IntegrationTestFiles/SystemTest1stIterationData/Choco/choco.config
  doc/UsageDoc/CA_UsageDocument.md
  src/LCT.Common/appSettings.json
  src/LCT.PackageIdentifier.UTest/ChocoProcessorTests.cs
  src/LCT.PackageIdentifier.UTest/DisplayInformationTests.cs
  src/LCT.PackageIdentifier.UTest/LCT.PackageIdentifier.UTest.csproj
  src/LCT.PackageIdentifier.UTest/NugetParserTests.cs
  src/LCT.PackageIdentifier.UTest/PackageIdentifierUTTestFiles/choco.config
  src/LCT.PackageIdentifier/ChocoProcessor.cs
  src/LCT.PackageIdentifier/NugetProcessor.cs
  src/LCT.PackageIdentifier/PemSignatureVerifier.cs
  src/LCT.SW360PackageCreator.UTest/PackageDownloaderTest.cs
  src/LCT.SW360PackageCreator/PackageDownloader.cs
  src/SW360IntegrationTest/Choco/PackageIdentifierInitialChoco.cs
  src/SW360IntegrationTest/PackageIdentifierTestFiles/Choco/CCTComparisonBOMChocoInitial.json
  src/TestUtilities/TestConstant.cs
  src/TestUtilities/TestParamChoco.cs
Labels: documentation, work in progress, Importance Low, UT/IT
