Repository siemens/continuous-clearing, pull requests merged in 2025-06, with the labels that each got.

#290 feat: release activities for 8.1.0
  .github/workflows/build-and-release.yml
  CA.nuspec
  src/ArtifactoryUploader/LCT.ArtifactoryUploader.csproj
  src/LCT.APICommunications/LCT.APICommunications.csproj
  src/LCT.Common/LCT.Common.csproj
  src/LCT.CycloneDxProcessor/LCT.CycloneDxProcessor.csproj
  src/LCT.Facade/LCT.Facade.csproj
  src/LCT.PackageIdentifier/LCT.PackageIdentifier.csproj
  src/LCT.SW360PackageCreator/LCT.SW360PackageCreator.csproj
  src/LCT.Services/LCT.Services.csproj
  src/LCT.Telemetry/LCT.Telemetry.csproj
Labels: enhancement, Importance Low, chore

#293 fix: Composition section on multi type project run
  src/LCT.Common/FileOperations.cs
  src/LCT.PackageIdentifier/BomCreator.cs
Labels: bug

#292 fix: Bug fixes for all exes
  src/AritfactoryUploader.UTest/PackageUploadHelperTest.cs
  src/ArtifactoryUploader/PackageUploadHelper.cs
  src/ArtifactoryUploader/PackageUploader.cs
  src/ArtifactoryUploader/Program.cs
  src/LCT.APICommunications.UTest/AttachmentHelperUTest.cs
  src/LCT.APICommunications.UTest/SW360ApicommunicationUTest.cs
  src/LCT.APICommunications/AttachmentHelper.cs
  src/LCT.APICommunications/Interfaces/ISW360APICommunication.cs
  src/LCT.APICommunications/SW360Apicommunication.cs
  src/LCT.Common/Constants/Dataconstant.cs
  src/LCT.Facade.UTest/SW360ApicommunicationFacadeTest.cs
  src/LCT.Facade/Interfaces/ISW360ApicommunicationFacade.cs
  src/LCT.Facade/SW360ApicommunicationFacade.cs
  src/LCT.SW360PackageCreator.UTest/ComponentCreatorTest.cs
  src/LCT.SW360PackageCreator.UTest/PackageDownloaderTest.cs
  src/LCT.SW360PackageCreator/ComponentCreator.cs
  src/LCT.SW360PackageCreator/CreatorHelper.cs
  src/LCT.SW360PackageCreator/PackageDownloader.cs
  src/LCT.SW360PackageCreator/Program.cs
  src/LCT.Services.UTest/Sw360CreatorServiceTest.cs
  src/LCT.Services/Interface/ISW360CreatorService.cs
  src/LCT.Services/Sw360CreatorService.cs
Labels: bug, Importance Low
