Repository siemens/continuous-clearing, pull requests merged in 2025-01, with the labels that each got.

#226 Updated new appsettings and UT and IT
  src/LCT.Common.UTests/CommonHelperTest.cs
  src/LCT.Common.UTests/FolderActionTest.cs
  src/LCT.Common/CommonAppSettings.cs
  src/LCT.Common/CommonHelper.cs
  src/LCT.Common/Constants/Dataconstant.cs
  src/LCT.Common/FolderAction.cs
  src/LCT.Common/Model/Config.cs
  src/LCT.Common/SettingsManager.cs
  src/LCT.Common/appSettings.json
  src/LCT.PackageIdentifier.UTest/AlpineParserTests.cs
  src/LCT.PackageIdentifier.UTest/BomHelperUnitTests.cs
  src/LCT.PackageIdentifier.UTest/BomValidatorUnitTests.cs
  src/LCT.PackageIdentifier.UTest/ConanParserTests.cs
  src/LCT.PackageIdentifier.UTest/CycloneBomProcessorTests.cs
  src/LCT.PackageIdentifier.UTest/DebianParserTests.cs
  src/LCT.PackageIdentifier.UTest/MavenParserTests.cs
  src/LCT.PackageIdentifier.UTest/NPMParserTests.cs
  src/LCT.PackageIdentifier.UTest/NpmProcessorUTest.cs
  src/LCT.PackageIdentifier.UTest/NugetParserTests.cs
  src/LCT.PackageIdentifier.UTest/PythonParserTests.cs
  src/LCT.PackageIdentifier/AlpineProcesser.cs
  src/LCT.PackageIdentifier/BomCreator.cs
  src/LCT.PackageIdentifier/BomValidator.cs
  src/LCT.PackageIdentifier/ConanProcessor.cs
  src/LCT.PackageIdentifier/CycloneBomProcessor.cs
  src/LCT.PackageIdentifier/DebianProcessor.cs
  src/LCT.PackageIdentifier/MavenProcessor.cs
  src/LCT.PackageIdentifier/NpmProcessor.cs
  src/LCT.PackageIdentifier/NugetProcessor.cs
  src/LCT.PackageIdentifier/Program.cs
  src/LCT.PackageIdentifier/PythonProcessor.cs
  src/LCT.PackageIdentifier/Scanner.cs
  src/LCT.Services/Sw360Service.cs
  src/SW360IntegrationTest/Conan/PackageIdentifierInitialConan.cs
  src/SW360IntegrationTest/Debian/PackageIdentifierInitialDebian.cs
  src/SW360IntegrationTest/Maven/PackageIdentifierInitialMaven.cs
  src/SW360IntegrationTest/NPM/PackageIdentifierInitial.cs
  src/SW360IntegrationTest/Nuget/NugetTemplate/ComponentCreatorNugetTemplate.cs
  src/SW360IntegrationTest/Nuget/NugetTemplate/PackageIdentifierNugetTemplate.cs
  src/SW360IntegrationTest/Nuget/PackageIdentifierInitialNuget.cs
  src/SW360IntegrationTest/Python/PackageIdentifierInitialPython.cs
  src/TestUtilities/TestConstant.cs
Labels: enhancement, Importance High

#236 Bug/publish artifact bug fix
  CA.nuspec
  src/ArtifactoryUploader/PackageUploadHelper.cs
  src/ArtifactoryUploader/Program.cs
  src/LCT.Common/CommonHelper.cs
  src/LCT.Common/LCT.Common.csproj
  src/LCT.Common/PipelineArtifactUploader.cs
  src/LCT.Common/SettingsManager.cs
  src/LCT.PackageIdentifier/Program.cs
  src/LCT.SW360PackageCreator/Program.cs
  src/LicenseClearingTool.sln
Labels: bug, Importance Low

#232 Feature/new app settings for creater
  src/LCT.Common/SettingsManager.cs
  src/LCT.SW360PackageCreator.UTest/ComponentCreatorTest.cs
  src/LCT.SW360PackageCreator.UTest/CreatorHelperTest.cs
  src/LCT.SW360PackageCreator.UTest/CreatorValidatorTest.cs
  src/LCT.SW360PackageCreator/ComponentCreator.cs
  src/LCT.SW360PackageCreator/CreatorHelper.cs
  src/LCT.SW360PackageCreator/CreatorValidator.cs
  src/LCT.SW360PackageCreator/DebianPackageDownloader.cs
  src/LCT.SW360PackageCreator/PackageDownloader.cs
  src/LCT.SW360PackageCreator/Program.cs
  src/LCT.SW360PackageCreator/URLHelper.cs
  src/SW360IntegrationTest/Alpine/ComponentCreatorInitialAlpine.cs
  src/SW360IntegrationTest/Conan/ComponentCreatorInitialConan.cs
  src/SW360IntegrationTest/Debian/ComponentCreatorInitialDebian.cs
  src/SW360IntegrationTest/Maven/ComponentCreatorInitialMaven.cs
  src/SW360IntegrationTest/NPM/ComponentCreatorInitial.cs
  src/SW360IntegrationTest/NPM/ComponentCreatorTestMode.cs
  src/SW360IntegrationTest/NPM/ComponentCreatorWithUpdatedComponents.cs
  src/SW360IntegrationTest/NPM/PackageIdentifierWithMultiplePackageLockInputs.cs
  src/SW360IntegrationTest/NPM/PackageIdentifierWithUpdatedComponents.cs
  src/SW360IntegrationTest/Nuget/ComponentCreatorInitialNuget.cs
  src/SW360IntegrationTest/Nuget/NugetTemplate/ComponentCreatorNugetTemplate.cs
  src/SW360IntegrationTest/Nuget/NugetTemplate/PackageIdentifierNugetTemplate.cs
  src/SW360IntegrationTest/Python/ComponentCreatorInitialPython.cs
Labels: enhancement, Importance High

#239 Package creater Input file path validation.
  src/LCT.Common/CommonAppSettings.cs
  src/SW360IntegrationTest/NPM/ComponentCreatorTestMode.cs
Labels: enhancement, Importance High

#241 New app settings for the artifactory uploader
  TestFiles/IntegrationTestFiles/ArtifactoryUploaderTestData/ComparisonBOM.json
  TestFiles/IntegrationTestFiles/ArtifactoryUploaderTestData/Conan/Test_Bom.cdx.json
  TestFiles/IntegrationTestFiles/ArtifactoryUploaderTestData/Npm/Test_Bom.cdx.json
  TestFiles/IntegrationTestFiles/ArtifactoryUploaderTestData/Nuget/Test_Bom.cdx.json
  TestFiles/IntegrationTestFiles/ArtifactoryUploaderTestData/Poetry/Test_Bom.cdx.json
  src/AritfactoryUploader.UTest/AritfactoryUploader.UTest.csproj
  src/AritfactoryUploader.UTest/ArtifactoryUTTestFiles/Test_Bom.cdx.json
  src/AritfactoryUploader.UTest/ArtifactoryUploaderTest.cs
  src/AritfactoryUploader.UTest/ArtifactoryValidatorTest.cs
  src/AritfactoryUploader.UTest/PackageUploadHelperTest.cs
  src/AritfactoryUploader.UTest/PackageUploaderTest.cs
  src/ArtifactoryUploader/ArtifactoryUploader.cs
  src/ArtifactoryUploader/ArtifactoryValidator.cs
  src/ArtifactoryUploader/Model/DisplayPackagesInfo.cs
  src/ArtifactoryUploader/Model/JfrogKey.cs
  src/ArtifactoryUploader/Model/UploaderKpiData.cs
  src/ArtifactoryUploader/PackageUploadHelper.cs
  src/ArtifactoryUploader/PackageUploader.cs
  src/ArtifactoryUploader/Program.cs
  src/LCT.APICommunications/DebianJfrogAPICommunication.cs
  src/LCT.APICommunications/JfrogApicommunication.cs
  src/LCT.APICommunications/JfrogAqlApiCommunication.cs
  src/LCT.APICommunications/MavenJfrogApiCommunication.cs
  src/LCT.APICommunications/Model/ArtifactoryCredentials.cs
  src/LCT.APICommunications/Model/ComponentsToArtifactory.cs
  src/LCT.APICommunications/NpmJfrogAPICommunication.cs
  src/LCT.APICommunications/NugetJfrogAPICommunication.cs
  src/LCT.APICommunications/PythonJfrogAPICommunication.cs
  src/LCT.Common/Constants/Dataconstant.cs
  src/LCT.Common/SettingsManager.cs
  src/LCT.PackageIdentifier/Program.cs
  src/SW360IntegrationTest/Conan/ArtifactoryUploaderConan.cs
  src/SW360IntegrationTest/Maven/ArtifactoryUploaderMaven.cs
  src/SW360IntegrationTest/NPM/ArtifactoryUploaderNpm.cs
  src/SW360IntegrationTest/Nuget/ArtifactoryUploaderNuget.cs
  src/SW360IntegrationTest/Python/ArtifactoryUploaderPython.cs
Labels: enhancement, Importance High

#243 Updated code changes for template
  TestFiles/IntegrationTestFiles/SystemTest1stIterationData/Nuget-Assets/Nuget_CATemplate.cdx.json
  src/ArtifactoryUploader/Program.cs
  src/LCT.APICommunications/DebianJfrogAPICommunication.cs
  src/LCT.APICommunications/NpmJfrogAPICommunication.cs
  src/LCT.APICommunications/NugetJfrogAPICommunication.cs
  src/LCT.APICommunications/SW360Apicommunication.cs
  src/LCT.Common/CommonHelper.cs
  src/LCT.Common/EnvironmentHelper.cs
  src/LCT.Common/Interface/IEnvironmentHelper.cs
  src/LCT.Common/PipelineArtifactUploader.cs
  src/LCT.Common/SettingsManager.cs
  src/LCT.PackageIdentifier.UTest/AlpineParserTests.cs
  src/LCT.PackageIdentifier.UTest/DebianParserTests.cs
  src/LCT.PackageIdentifier.UTest/MavenParserTests.cs
  src/LCT.PackageIdentifier.UTest/NPMParserTests.cs
  src/LCT.PackageIdentifier.UTest/PythonParserTests.cs
  src/LCT.PackageIdentifier.UTest/SBomTemplateTests.cs
  src/LCT.PackageIdentifier/AlpineProcesser.cs
  src/LCT.PackageIdentifier/ConanProcessor.cs
  src/LCT.PackageIdentifier/DebianProcessor.cs
  src/LCT.PackageIdentifier/MavenProcessor.cs
  src/LCT.PackageIdentifier/NpmProcessor.cs
  src/LCT.PackageIdentifier/NugetProcessor.cs
  src/LCT.PackageIdentifier/Program.cs
  src/LCT.PackageIdentifier/PythonProcessor.cs
  src/LCT.PackageIdentifier/SbomTemplate.cs
  src/LCT.PackageIdentifier/Scanner.cs
  src/LCT.SW360PackageCreator/ComponentCreator.cs
  src/LCT.SW360PackageCreator/Program.cs
  src/LCT.Services.UTest/Sw360ServiceTest.cs
  src/LCT.Services/Sw360Service.cs
  src/SW360IntegrationTest/Nuget/NugetTemplate/ComponentCreatorNugetTemplate.cs
Labels: bug, Importance High

#245 Added new property internal:siemens:clearing:sw360:exclude to exclude components from Sw360, but retain them in the SBOM
  src/LCT.Common.UTests/CommonHelperTest.cs
  src/LCT.Common/CommonHelper.cs
  src/LCT.Common/Constants/Dataconstant.cs
  src/LCT.Common/Model/Components.cs
  src/LCT.PackageIdentifier.UTest/ConanParserTests.cs
  src/LCT.PackageIdentifier/Model/BomKpiData.cs
  src/LCT.SW360PackageCreator/ComponentCreator.cs
Labels: enhancement, Importance Low
