Repository siemens/continuous-clearing, pull requests merged in 2025-02, with the labels that each got.

#248 Adding Unit tests for the PipelineArtifactUploader class
  src/LCT.Common.UTests/PipelineArtifactUploaderTest.cs
Labels: Importance Low, Refactoring

#244 Bug fix for NPM dependency issue
  src/LCT.PackageIdentifier.UTest/MavenParserTests.cs
  src/LCT.PackageIdentifier/ConanProcessor.cs
  src/LCT.PackageIdentifier/DebianProcessor.cs
  src/LCT.PackageIdentifier/MavenProcessor.cs
  src/LCT.PackageIdentifier/NpmProcessor.cs
  src/LCT.PackageIdentifier/NugetProcessor.cs
  src/LCT.PackageIdentifier/PythonProcessor.cs
Labels: bug, Importance Low

#247 Refactored the PackageUploadHelper class on Artifactory Uploader
  src/AritfactoryUploader.UTest/ArtifactoryUploaderTest.cs
  src/AritfactoryUploader.UTest/JfrogRepoUpdaterTest.cs
  src/AritfactoryUploader.UTest/PackageUploadHelperTest.cs
  src/AritfactoryUploader.UTest/PackageUploadInformationTest.cs
  src/AritfactoryUploader.UTest/PackageUploaderTest.cs
  src/AritfactoryUploader.UTest/UploadToArtifactoryTest.cs
  src/ArtifactoryUploader/ArtifactoryUploader.cs
  src/ArtifactoryUploader/JfrogRepoUpdater.cs
  src/ArtifactoryUploader/PackageUploadHelper.cs
  src/ArtifactoryUploader/PackageUploadInformation.cs
  src/ArtifactoryUploader/PackageUploader.cs
  src/ArtifactoryUploader/Program.cs
  src/ArtifactoryUploader/UploadToArtifactory.cs
  src/LCT.Common/CommonHelper.cs
  src/LCT.Common/EnvironmentHelper.cs
  src/LCT.PackageIdentifier.UTest/DisplayInformationTests.cs
  src/LCT.PackageIdentifier/DisplayInformation.cs
  src/LCT.PackageIdentifier/Program.cs
Labels: enhancement, Importance Low, Refactoring

#249 Minor code corrections in all excs code level
  src/ArtifactoryUploader/Program.cs
  src/LCT.APICommunications/DebianJfrogAPICommunication.cs
  src/LCT.APICommunications/NpmJfrogAPICommunication.cs
  src/LCT.APICommunications/NugetJfrogAPICommunication.cs
  src/LCT.APICommunications/SW360Apicommunication.cs
  src/LCT.Common.UTests/PipelineArtifactUploaderTest.cs
  src/LCT.Common/EnvironmentHelper.cs
  src/LCT.Common/SettingsManager.cs
  src/LCT.PackageIdentifier/AlpineProcesser.cs
  src/LCT.PackageIdentifier/BomHelper.cs
  src/LCT.PackageIdentifier/ConanProcessor.cs
  src/LCT.PackageIdentifier/DebianProcessor.cs
  src/LCT.PackageIdentifier/MavenProcessor.cs
  src/LCT.PackageIdentifier/Model/BomKpiData.cs
  src/LCT.PackageIdentifier/NpmProcessor.cs
  src/LCT.PackageIdentifier/NugetProcessor.cs
  src/LCT.PackageIdentifier/Program.cs
  src/LCT.PackageIdentifier/PythonProcessor.cs
  src/LCT.PackageIdentifier/Scanner.cs
  src/LCT.SW360PackageCreator/Program.cs
Labels: Importance Low, Refactoring

#251 CA Tool telemetry
  src/ArtifactoryUploader/LCT.ArtifactoryUploader.csproj
  src/ArtifactoryUploader/Program.cs
  src/LCT.Common/CommonAppSettings.cs
  src/LCT.Common/Constants/TelemetryConstant.cs
  src/LCT.Common/LCT.Common.csproj
  src/LCT.Common/TelemetryHelper.cs
  src/LCT.Common/appSettings.json
  src/LCT.PackageIdentifier/LCT.PackageIdentifier.csproj
  src/LCT.PackageIdentifier/Program.cs
  src/LCT.SW360PackageCreator/ComponentCreator.cs
  src/LCT.SW360PackageCreator/CreatorHelper.cs
  src/LCT.SW360PackageCreator/LCT.SW360PackageCreator.csproj
  src/LCT.SW360PackageCreator/Program.cs
  src/LCT.Telemetry/ApplicationInsightsTelemetryProvider.cs
  src/LCT.Telemetry/HashUtility.cs
  src/LCT.Telemetry/ITelemetryProvider.cs
  src/LCT.Telemetry/LCT.Telemetry.csproj
  src/LCT.Telemetry/Telemetry.cs
  src/LCT.Telemetry/TelemetryProviderFactory.cs
  src/LicenseClearingTool.sln
  src/SW360IntegrationTest/Alpine/ComponentCreatorInitialAlpine.cs
  src/SW360IntegrationTest/Alpine/PackageIdentifierInitialAlpine.cs
  src/SW360IntegrationTest/Conan/ArtifactoryUploaderConan.cs
  src/SW360IntegrationTest/Conan/ComponentCreatorInitialConan.cs
  src/SW360IntegrationTest/Conan/PackageIdentifierInitialConan.cs
  src/SW360IntegrationTest/Debian/ComponentCreatorInitialDebian.cs
  src/SW360IntegrationTest/Debian/PackageIdentifierInitialDebian.cs
  src/SW360IntegrationTest/Maven/ArtifactoryUploaderMaven.cs
  src/SW360IntegrationTest/Maven/ComponentCreatorInitialMaven.cs
  src/SW360IntegrationTest/Maven/PackageIdentifierInitialMaven.cs
  src/SW360IntegrationTest/NPM/ArtifactoryUploaderNpm.cs
  src/SW360IntegrationTest/NPM/ComponentCreatorInitial.cs
  src/SW360IntegrationTest/NPM/ComponentCreatorTestMode.cs
  src/SW360IntegrationTest/NPM/ComponentCreatorWithUpdatedComponents.cs
  src/SW360IntegrationTest/NPM/PackageIdentifierInitial.cs
  src/SW360IntegrationTest/NPM/PackageIdentifierInitialTestMode.cs
  src/SW360IntegrationTest/NPM/PackageIdentifierWithMultiplePackageLockInputs.cs
  src/SW360IntegrationTest/NPM/PackageIdentifierWithUpdatedComponents.cs
  src/SW360IntegrationTest/Nuget/ArtifactoryUploaderNuget.cs
  src/SW360IntegrationTest/Nuget/ComponentCreatorInitialNuget.cs
  src/SW360IntegrationTest/Nuget/NugetTemplate/ComponentCreatorNugetTemplate.cs
  src/SW360IntegrationTest/Nuget/NugetTemplate/PackageIdentifierNugetTemplate.cs
  src/SW360IntegrationTest/Nuget/PackageIdentifierInitialNuget.cs
  src/SW360IntegrationTest/Python/ArtifactoryUploaderPython.cs
  src/SW360IntegrationTest/Python/ComponentCreatorInitialPython.cs
  src/SW360IntegrationTest/Python/PackageIdentifierInitialPython.cs
  src/Telemetry.UTest/LCT.Telemetry.UTest.csproj
  src/Telemetry.UTest/Telemetry.UTest.cs
  src/TestUtilities/TestConstant.cs
  src/TestUtilities/TestParam.cs
  src/TestUtilities/TestParamAlpine.cs
  src/TestUtilities/TestParamConan.cs
  src/TestUtilities/TestParamDebian.cs
  src/TestUtilities/TestParamMaven.cs
  src/TestUtilities/TestParamNuget.cs
  src/TestUtilities/appSettingsSW360IntegrationTest.json
Labels: enhancement, Importance Low
