Repository siemens/continuous-clearing, pull requests merged in 2025-03, with the labels that each got.

#254 CA Tool Sonar issue fixes
  src/ArtifactoryUploader/ArtifactoryUploader.cs
  src/ArtifactoryUploader/JfrogRepoUpdater.cs
  src/LCT.Common/TelemetryHelper.cs
  src/LCT.PackageIdentifier/ConanProcessor.cs
  src/LCT.PackageIdentifier/MavenProcessor.cs
  src/LCT.PackageIdentifier/NpmProcessor.cs
  src/LCT.PackageIdentifier/NugetDevDependencyParser.cs
  src/LCT.PackageIdentifier/NugetProcessor.cs
  src/LCT.SW360PackageCreator/CreatorValidator.cs
Labels: Importance Low, Refactoring, Under Review

#255 Continuous Clearing Tool code coverage reached to 80%
  src/AritfactoryUploader.UTest/PackageUploadInformationTest.cs
  src/LCT.APICommunications.UTest/AttachmentHelperUTest.cs
  src/LCT.APICommunications.UTest/DebianJfrogAPICommunicationUTest.cs
  src/LCT.APICommunications.UTest/JfrogAqlApiCommunicationUTest.cs
  src/LCT.APICommunications.UTest/NPMJfrogAPICommunicationUTest.cs
  src/LCT.APICommunications.UTest/PythonJfrogApiCommunicationUTest.cs
  src/LCT.APICommunications.UTest/SW360ApicommunicationUTest.cs
  src/LCT.Common.UTests/FolderActionTest.cs
  src/LCT.Common.UTests/SettingsManagerTests.cs
  src/LCT.SW360PackageCreator.UTest/ComponentCreatorTest.cs
  src/LCT.SW360PackageCreator.UTest/UrlHelperTest.cs
Labels: Importance Low, Refactoring, Under Review

#252 Retry API requests to SW360 and FOSSology Urls.
  doc/UsageDoc/CA_UsageDocument.md
  src/LCT.APICommunications.UTest/RetryHttpClientHandlerUTest.cs
  src/LCT.APICommunications/ApiConstant.cs
  src/LCT.APICommunications/DebianJfrogAPICommunication.cs
  src/LCT.APICommunications/JfrogApicommunication.cs
  src/LCT.APICommunications/JfrogAqlApiCommunication.cs
  src/LCT.APICommunications/LCT.APICommunications.csproj
  src/LCT.APICommunications/MavenJfrogApiCommunication.cs
  src/LCT.APICommunications/NpmJfrogAPICommunication.cs
  src/LCT.APICommunications/NugetJfrogAPICommunication.cs
  src/LCT.APICommunications/PythonJfrogAPICommunication.cs
  src/LCT.APICommunications/RetryHttpClientHandler.cs
  src/LCT.APICommunications/SW360Apicommunication.cs
  src/LCT.PackageIdentifier/LCT.PackageIdentifier.csproj
  src/LCT.SW360PackageCreator/URLHelper.cs
Labels: enhancement, Importance Low, Under Review

#258 Support Linux Compatibility and Improve Path Handling
  src/SW360IntegrationTest/Alpine/ComponentCreatorInitialAlpine.cs
  src/SW360IntegrationTest/Alpine/PackageIdentifierBasicSBOMAlpine.cs
  src/SW360IntegrationTest/Alpine/PackageIdentifierInitialAlpine.cs
  src/SW360IntegrationTest/Conan/ArtifactoryUploaderConan.cs
  src/SW360IntegrationTest/Conan/ComponentCreatorInitialConan.cs
  src/SW360IntegrationTest/Conan/PackageIdentifierBasicSBOMConan.cs
  src/SW360IntegrationTest/Conan/PackageIdentifierInitialConan.cs
  src/SW360IntegrationTest/Debian/ComponentCreatorInitialDebian.cs
  src/SW360IntegrationTest/Debian/PackageIdentifierBasicSBOMDebian.cs
  src/SW360IntegrationTest/Debian/PackageIdentifierInitialDebian.cs
  src/SW360IntegrationTest/Maven/ArtifactoryUploaderMaven.cs
  src/SW360IntegrationTest/Maven/ComponentCreatorInitialMaven.cs
  src/SW360IntegrationTest/Maven/PackageIdentifierBasicSBOMMaven.cs
  src/SW360IntegrationTest/Maven/PackageIdentifierInitialMaven.cs
  src/SW360IntegrationTest/NPM/ArtifactoryUploaderNpm.cs
  src/SW360IntegrationTest/NPM/ClearingToolLoadTest.cs
  src/SW360IntegrationTest/NPM/ComponentCreatorInitial.cs
  src/SW360IntegrationTest/NPM/ComponentCreatorTestMode.cs
  src/SW360IntegrationTest/NPM/ComponentCreatorWithUpdatedComponents.cs
  src/SW360IntegrationTest/NPM/PackageIdentifierBasicSBOMNpm.cs
  src/SW360IntegrationTest/NPM/PackageIdentifierInitial.cs
  src/SW360IntegrationTest/NPM/PackageIdentifierInitialTestMode.cs
  src/SW360IntegrationTest/NPM/PackageIdentifierWithMultiplePackageLockInputs.cs
  src/SW360IntegrationTest/NPM/PackageIdentifierWithUpdatedComponents.cs
  src/SW360IntegrationTest/Nuget/ArtifactoryUploaderNuget.cs
  src/SW360IntegrationTest/Nuget/ComponentCreatorInitialNuget.cs
  src/SW360IntegrationTest/Nuget/NugetTemplate/ComponentCreatorNugetTemplate.cs
  src/SW360IntegrationTest/Nuget/NugetTemplate/PackageIdentifierNugetTemplate.cs
  src/SW360IntegrationTest/Nuget/PackageIdentifierBasicSBOMNuget.cs
  src/SW360IntegrationTest/Nuget/PackageIdentifierInitialNuget.cs
  src/SW360IntegrationTest/Python/ArtifactoryUploaderPython.cs
  src/SW360IntegrationTest/Python/ComponentCreatorInitialPython.cs
  src/SW360IntegrationTest/Python/PackageIdentifierBasicSBOMPython.cs
  src/SW360IntegrationTest/Python/PackageIdentifierInitialPython.cs
  src/TestUtilities/TestHelper.cs
  src/UnitTestUtilities/appsettingsUnitTest.json
Labels: Importance Low, Refactoring

#259 Improve Cross-Platform Compatibility in Tests and Refactor Path Handling
  src/AritfactoryUploader.UTest/PackageUploadHelperTest.cs
  src/AritfactoryUploader.UTest/PackageUploaderTest.cs
  src/LCT.APICommunications.UTest/SW360ApicommunicationUTest.cs
  src/LCT.Common.UTests/RuntimeEnvironmentTests.cs
  src/LCT.PackageIdentifier.UTest/AlpineParserTests.cs
  src/LCT.PackageIdentifier.UTest/BOMCreatorTests.cs
  src/LCT.PackageIdentifier.UTest/ConanParserTests.cs
  src/LCT.PackageIdentifier.UTest/CycloneBomProcessorTests.cs
  src/LCT.PackageIdentifier.UTest/DebianParserTests.cs
  src/LCT.PackageIdentifier.UTest/DisplayInformationTests.cs
  src/LCT.PackageIdentifier.UTest/MavenParserTests.cs
  src/LCT.PackageIdentifier.UTest/NPMParserTests.cs
  src/LCT.PackageIdentifier.UTest/NugetParserTests.cs
  src/LCT.PackageIdentifier.UTest/PythonParserTests.cs
  src/LCT.PackageIdentifier.UTest/ScannerTests.cs
  src/LCT.SW360PackageCreator.UTest/ComponentCreatorTest.cs
  src/LCT.SW360PackageCreator.UTest/CreatorHelperTest.cs
Labels: Importance Low, Refactoring, Under Review

#261 chore(pipeline): integrate Azure Pipeline with Continuous Clearing Tool
  .github/workflows/build-and-release.yml
  .github/workflows/compile.yml
  .github/workflows/pr-checks.yml
  pipelines/azure-pipelines-UT-IT-Sonar.yml
Labels: enhancement, Importance Low, Refactoring, Under Review
