Repository siemens/continuous-clearing, pull requests merged in 2025-04, with the labels that each got.

#263 test: Adding missing tests to make the CAtool coverage to 80 percent
  src/AritfactoryUploader.UTest/JfrogRepoUpdaterTest.cs
  src/LCT.APICommunications.UTest/NPMJfrogAPICommunicationUTest.cs
  src/LCT.Common.UTests/SettingsManagerTests.cs
  src/LCT.SW360PackageCreator.UTest/CreatorValidatorTest.cs
  src/LCT.SW360PackageCreator.UTest/DebianPackageDownloaderTest.cs
  src/LCT.SW360PackageCreator.UTest/UrlHelperTest.cs
  src/LCT.Services.UTest/JFrogServiceUTest.cs
  src/LCT.Services.UTest/Sw360CommonServiceTest.cs
  src/Telemetry.UTest/Telemetry.UTest.cs
Labels: Importance Low, Refactoring, Under Review

#264 chore: merge development into release/v8.0.0-rc
  src/AritfactoryUploader.UTest/JfrogRepoUpdaterTest.cs
  src/LCT.APICommunications.UTest/NPMJfrogAPICommunicationUTest.cs
  src/LCT.Common.UTests/SettingsManagerTests.cs
  src/LCT.SW360PackageCreator.UTest/CreatorValidatorTest.cs
  src/LCT.SW360PackageCreator.UTest/DebianPackageDownloaderTest.cs
  src/LCT.SW360PackageCreator.UTest/UrlHelperTest.cs
  src/LCT.Services.UTest/JFrogServiceUTest.cs
  src/LCT.Services.UTest/Sw360CommonServiceTest.cs
  src/Telemetry.UTest/Telemetry.UTest.cs
Labels: Under Review, chore

#266 ci(pipeline): add and update Azure Pipelines with caching, environment fixes, and improved tests
  pipelines/azure-pipelines-UT-IT-Sonar.yml
  pipelines/build/azure-pipelines-build-run.yml
  pipelines/templates/azure-pipelines-start-sw360-fossology-containers-template.yml
  pipelines/templates/azure-pipelines-syft-generate-sbom-template.yml
  pipelines/templates/build/azure-pipelines-clearing-tool-build-run-binary-step-template.yml
  pipelines/templates/build/azure-pipelines-clearing-tool-build-run-image-step-template.yml
  pipelines/templates/build/azure-pipelines-clearing-tool-build-run-job-template.yml
  pipelines/templates/build/azure-pipelines-clearing-tool-build-run-stage-template.yml
  src/AritfactoryUploader.UTest/UploadToArtifactoryTest.cs
  src/ArtifactoryUploader/Program.cs
  src/ArtifactoryUploader/UploadToArtifactory.cs
  src/LCT.APICommunications.UTest/AttachmentHelperUTest.cs
  src/LCT.Common.UTests/PipelineArtifactUploaderTest.cs
  src/LCT.Common.UTests/RuntimeEnvironmentTests.cs
  src/LCT.Common/CommonAppSettings.cs
  src/LCT.Common/Logging/Log4net.cs
  src/LCT.Common/PipelineArtifactUploader.cs
  src/LCT.Common/Runtime/RuntimeEnvironment.cs
  src/LCT.Facade/SW360ApicommunicationFacade.cs
  src/LCT.PackageIdentifier.UTest/ConanParserTests.cs
  src/LCT.PackageIdentifier/ConanProcessor.cs
  src/LCT.PackageIdentifier/Program.cs
  src/LCT.SW360PackageCreator/ComponentCreator.cs
  src/LCT.SW360PackageCreator/Program.cs
  src/SW360IntegrationTest/NPM/ComponentCreatorTestMode.cs
Labels: Importance Low, Refactoring, chore

#267 ci(pipeline): add and update Azure Pipelines with caching, environmen…
  pipelines/azure-pipelines-UT-IT-Sonar.yml
  pipelines/build/azure-pipelines-build-run.yml
  pipelines/templates/azure-pipelines-start-sw360-fossology-containers-template.yml
  pipelines/templates/azure-pipelines-syft-generate-sbom-template.yml
  pipelines/templates/build/azure-pipelines-clearing-tool-build-run-binary-step-template.yml
  pipelines/templates/build/azure-pipelines-clearing-tool-build-run-image-step-template.yml
  pipelines/templates/build/azure-pipelines-clearing-tool-build-run-job-template.yml
  pipelines/templates/build/azure-pipelines-clearing-tool-build-run-stage-template.yml
  src/AritfactoryUploader.UTest/UploadToArtifactoryTest.cs
  src/ArtifactoryUploader/Program.cs
  src/ArtifactoryUploader/UploadToArtifactory.cs
  src/LCT.APICommunications.UTest/AttachmentHelperUTest.cs
  src/LCT.Common.UTests/PipelineArtifactUploaderTest.cs
  src/LCT.Common.UTests/RuntimeEnvironmentTests.cs
  src/LCT.Common/CommonAppSettings.cs
  src/LCT.Common/Logging/Log4net.cs
  src/LCT.Common/PipelineArtifactUploader.cs
  src/LCT.Common/Runtime/RuntimeEnvironment.cs
  src/LCT.Facade/SW360ApicommunicationFacade.cs
  src/LCT.PackageIdentifier.UTest/ConanParserTests.cs
  src/LCT.PackageIdentifier/ConanProcessor.cs
  src/LCT.PackageIdentifier/Program.cs
  src/LCT.SW360PackageCreator/ComponentCreator.cs
  src/LCT.SW360PackageCreator/Program.cs
  src/SW360IntegrationTest/NPM/ComponentCreatorTestMode.cs
Labels: Importance Low, Refactoring, chore
