Repository siemens/continuous-clearing, pull requests merged in 2025-08, with the labels that each got.

#310 fix: Bugfix for remove duplicate properties in package creater while updateing SBOM, Identify debian component by using package url for avoiding create duplicate components.
  src/AritfactoryUploader.UTest/PackageUploadHelperTest.cs
  src/ArtifactoryUploader/PackageUploadHelper.cs
  src/LCT.Common.UTests/CommonHelperTest.cs
  src/LCT.Common/CommonHelper.cs
  src/LCT.PackageIdentifier/ConanProcessor.cs
  src/LCT.PackageIdentifier/CycloneBomProcessor.cs
  src/LCT.PackageIdentifier/DebianProcessor.cs
  src/LCT.PackageIdentifier/MavenProcessor.cs
  src/LCT.PackageIdentifier/NpmProcessor.cs
  src/LCT.PackageIdentifier/NugetProcessor.cs
  src/LCT.PackageIdentifier/PythonProcessor.cs
  src/LCT.PackageIdentifier/SbomTemplate.cs
  src/LCT.SW360PackageCreator/CreatorHelper.cs
  src/LCT.Services/Sw360CommonService.cs
Labels: bug, work in progress, Importance High

#322 fix: updating the trigger and checkout branch
  pipelines/build/azure-pipelines-build-run.yml
  pipelines/templates/build/azure-pipelines-clearing-tool-build-run-job-template.yml
Labels: bug, Importance High

#324 feat: Implemented UnitTest.
  src/LCT.Common.UTests/LoggerFactoryTest.cs
  src/LCT.Common.UTests/LoggerHelperTest.cs
  src/LCT.Common.UTests/SpectreLogAdapterTest.cs
  src/LCT.Common/Logging/LoggerHelper.cs
Labels: Importance Low, Refactoring, Under Review
